<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class QuestionAnswerTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('question_answer_types')->insert([
            [
                'id' => 1,
                'name_en' => 'Single Choice (SCQ)',
                'name_kh' => 'ចម្លើយតែមួយ',
                'desc_en' => 'Students select one answer from several options',
                'desc_kh' => '',
                'input' => 'radio',
                'view' => 'option',
                'slug' => 'scq',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name_en' => 'Multiple Choice (MCQ)',
                'name_kh' => 'ចម្លើយច្រើន',
                'desc_en' => 'Students select several answers from several options.',
                'desc_kh' => '',
                'input' => 'checkbox',
                'view' => 'option',
                'slug' => 'mcq',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name_en' => 'Short Text',
                'name_kh' => 'ចម្លើយខ្លី',
                'desc_en' => 'Students writing answer < 255 characters.',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'short_text',
                'slug' => 'short-text',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name_en' => 'Writing',
                'name_kh' => 'តែងសេចក្តី',
                'desc_en' => 'Type an Essay',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'writing',
                'slug' => 'writing',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name_en' => 'True/False',
                'name_kh' => 'ចម្លើយខុស/ត្រូវ',
                'desc_en' => 'Write True or False',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'option',
                'slug' => 'true-false',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name_en' => 'File Upload',
                'name_kh' => 'បញ្ចូលឯកសារ',
                'desc_en' => 'Students upload the image for the answer.',
                'desc_kh' => '',
                'input' => 'file',
                'view' => 'file_upload',
                'slug' => 'file-upload',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name_en' => 'Gap Filling',
                'name_kh' => 'បំពេញចន្លោះ',
                'desc_en' => 'Students fill the gap by input.',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'gap_filling',
                'slug' => 'gap-filling',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name_en' => 'Matching',
                'name_kh' => 'ផ្គូផ្គង',
                'desc_en' => '',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'matching.item_edit',
                'slug' => 'matching',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name_en' => 'Ordering',
                'name_kh' => 'រៀបតាមលំដាប់',
                'desc_en' => '',
                'desc_kh' => '',
                'input' => 'text',
                'view' => 'option',
                'slug' => 'ordering',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
